# Generated by Django 4.0.3 on 2022-04-07 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelList',
            fields=[
                ('hotel_name', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(default=0)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('checkin', models.CharField(max_length=120)),
                ('checkout', models.CharField(max_length=120)),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapi.hotellist')),
            ],
        ),
        migrations.CreateModel(
            name='GuestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=120)),
                ('guest_gender', models.CharField(max_length=30)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapi.reservation')),
            ],
        ),
    ]
