# Generated by Django 4.0.2 on 2022-03-01 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_location',
        ),
    ]
