# Generated by Django 4.0.3 on 2022-03-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapi', '0002_remove_hotel_hotel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.IntegerField(),
        ),
    ]
