# Generated by Django 4.0.3 on 2022-03-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapi', '0003_hotel_availability_alter_hotel_hotel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
