# Generated by Django 4.0.3 on 2022-03-12 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapi', '0004_hotelapi_delete_hotel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelAPI',
            new_name='Hotel',
        ),
    ]
