# Generated by Django 4.0.3 on 2022-03-12 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapi', '0006_hotel_checkin_hotel_checkout_hotel_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=60)),
                ('checkin', models.DateField(default=datetime.date.today)),
                ('checkout', models.DateField(default=datetime.date(2022, 3, 13))),
                ('guest_name', models.CharField(default='John Doe', max_length=60)),
                ('gender', models.CharField(default='M', max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='guest_name',
        ),
    ]
