# Generated by Django 4.0.3 on 2022-03-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapi', '0007_reservation_remove_hotel_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='gender',
            field=models.CharField(max_length=6),
        ),
    ]
